### ISSUE TITLE
Allow reading config from "well known" location

### ISSUE THREAD

**Issue by cronhan** [h1romas4/zellij-datetime#3]
At the moment reading the config file from the startup directory is a) unexpected and b) annoying. 

Suggest to add functionality to also look for the file in `$HOME/.config/zellij` and/or `$ZELLIJ_CONFIG_DIR`.

**Comment by h1romas4** [comment]
I agree that the current option designation is unexpected.

The following plugin options will be available starting with Zellij 0.38 and are planned to be changed.

```
layout {
    pane size=1 borderless=true {
        plugin location="file:./target/wasm32-wasi/debug/zellij-datetime.wasm" {
            timezone1 "UTC:0"
            timezone2 "PDT:-9"
            timezone3 "JST:+9"
            background_color "#ffffff"
            default_timezone "JST"
        }
    }
    pane
}
```

(I would think a little more about formatting, since this specification is key-value and not a tree structure.)

**Comment by h1romas4** [comment]
zellij-datetime v0.17.0 now supports the new plugin configuration for Zellij 0.38.

```
layout {
    pane size=1 borderless=true {
        plugin location="file:./target/wasm32-wasi/debug/zellij-datetime.wasm" {
            timezone1 "PDT/-9"
            timezone2 "UTC/0"
            timezone3 "CEST/+2"
            timezone4 "JST/+9"
            default_timezone "JST"
            background_color "#0080a0"
            foreground_color "#ffffff"
            pane_color "#1e1e1e"
            enable_right_click false
        }
    }
    pane
}
```

[add support plugin config and permission system on zellij 0.38](https://github.com/h1romas4/zellij-datetime/commit/3cff9b3ef619755308829d8accbeed0d4fae9dc4)

**Comment by cronhan** [comment]
Thanks, working perfect!
