### ISSUE TITLE
Add hint how to correctly add zellij-datetime on same line as other bars to readme

### ISSUE THREAD

**Issue by ghost** [h1romas4/zellij-datetime#6]
Hey, thanks for the plugin. The default config from the readme, as far as I can see, doesn't put the bar on the same line as the other bar(s), unless I'm doing something wrong. I've now arrived at a layout like this:

```kdl
layout {
    pane split_direction="vertical" size=1 {
        pane size="70%" borderless=true {
            plugin location="compact-bar"
        }
        pane size="30%" borderless=true {
            plugin location="file:/Users/user1/.config/zellij/plugins/zellij-datetime.wasm" {
                timezone1 "UTC/0"
                default_timezone "UTC"
            }
        }
    }

    pane
}
```

Is that how it's intended to be done? 

Either way, I think its fair to assume that this plugin might be the first point of contact with the plugin and layout ecosystem for ppl new to zellij like me, so it might be worth a short section in the README. Though I'd understand if you said this was better suited for the zellij docs themselves.

**Comment by h1romas4** [comment]
You are correcft, as pointed out. I fixed it, thank you so much!
