### ISSUE TITLE
[feature request] default to system clock without specifying a timezone

### ISSUE THREAD

**Issue by pirafrank** [h1romas4/zellij-datetime#8]
By default the plugin should add option to or default to showing the system datetime. This allows, for example, to avoid changing the config twice a year for countries adhering DST, Daylight Saving Time.

**Comment by h1romas4** [comment]
Thank you for your comment.

The current WebAssembly/WASIp1 API as far as I know cannot get the timezone from the OS, only the UTC time.

So to display OS system time, we will have to wait for WASI (wasip2?) and Zellij's WebAssembly Runtime version to be upgraded.
